### PR TITLE
do not need cedar api key arg when instantiating upload

### PR DESCRIPTION
**Pull request by gesinaphillips**
Changed to support ingest-validation-tools

### CODE REVIEW

**Comment by jpuerto-psc** [comment]
@gesinaphillips - if this is a breaking change please make sure to coordinate with @yuanzhou since there may be some change needed in Ingest API as well.

**Comment by gesinaphillips** [comment]
> @gesinaphillips - if this is a breaking change please make sure to coordinate with @yuanzhou since there may be some change needed in Ingest API as well.

You're right, @jpuerto-psc, there are implications for ingest-api here. @yuanzhou this change would affect `src > routes > validation > __init__.py` because it needs to pass a globus_token instead of a cedar_api_key (which can be removed entirely). How would you like to proceed?

**Comment by yuanzhou** [comment]
@jpuerto-psc and @gesinaphillips thanks for the heads-up. Currently in ingest-api `src/routes/validation/__init__.py`, we import the following modules from ingest-validation-tools: 
```
ingest_validation_tools_upload = import_module('ingest_validation_tools.upload')
ingest_validation_tools_error_report = import_module('ingest_validation_tools.error_report')
ingest_validation_tools_validation_utils = import_module('ingest_validation_tools.validation_utils')
ingest_validation_tools_plugin_validator = import_module('ingest_validation_tools.plugin_validator')
ingest_validation_tools_schema_loader = import_module('ingest_validation_tools.schema_loader')
ingest_validation_tools_table_validator = import_module('ingest_validation_tools.table_validator')
```
1. Can you point me to where this change should happen?

2. Can you also add me to the reviewers list for any metadata validation updates in the future? We want to make sure:
- the changes made in ingest-validation-tools doesn't cause any issues to the ingest-api
- once this PR gets merged into `devel`, on our end we'll need to redeploy ingest-api on DEV by pointing to the latest `devel` as a submodule reference and verify
- please also tag me in the PR when things get merged into `main` for your release purpose, so we can coordinate based on the release schedule of ingest-api for PROD.

**Comment by gesinaphillips** [comment]
Hey @yuanzhou here's a branch in ingest-api showing how I think the change would look: https://github.com/hubmapconsortium/ingest-api/compare/main...phillips/validation_update

I am not sure about the `globus_token` var, that might not be the correct way to get the token.

If this is somehow correct-looking I can submit a PR, but otherwise, I hope this helps show where the change would need to go.

**Comment by yuanzhou** [comment]
@gesinaphillips thanks, please feel free to create a PR into the `dev-integrate` branch in ingest-api, and we'll go from there. Will you be making the corresponding changes in the ingest-validation-tools code too? When I deploy ingest-api with your changes, I'll point to the corresponding branch in ingest-validation-tools and install as a submodule. The changes in this PR is for ingest-pipeline, not sure when you'll redeploy to the Airflow. We'll need to coordinate.

**Comment by gesinaphillips** [comment]
@yuanzhou ingest-validation-tools is getting a big update, which has prompted all of this: https://github.com/hubmapconsortium/ingest-validation-tools/pull/1245. This change should really only affect how uploads are instantiated and/or how get_tsv_errors is called. It is not yet merged, I think because we're trying to clear up the necessary changes in ingest-pipeline (this PR) and ingest-api ([this new PR](https://github.com/hubmapconsortium/ingest-api/pull/418)). 

I feel like we're pretty close to getting everything merged. The ingest-api PR needs a look-over. As for this ingest-pipeline PR, @jpuerto-psc @sunset666 what do you think?

**Comment by jpuerto-psc** [comment]
@sunset666 - please review when possible

**Review by sunset666 — APPROVED** [review]

**Pull request merged**
